In [2]:
import numpy as np

In [4]:
marks = [8, 8, 10, 2, 3, 10, 1, 6, 7, 8]

In [2]:
marks = [8, 8, 10, 2, 3, 10, 1, 6, 7, 8]

In [7]:
marks_n = np.array(marks, dtype=np.int16) 
print marks_n
print type(marks_n)
print marks_n.ndim # shows dimension of an array
print marks_n.dtype
print marks_n.shape

[ 8  8 10  2  3 10  1  6  7  8]
<type 'numpy.ndarray'>
1
int16
(10L,)


In [9]:
deducted_by_1 = marks_n - 1
print deducted_by_1
print type(deducted_by_1)

[7 7 9 1 2 9 0 5 6 7]
<type 'numpy.ndarray'>


In [10]:
doubled_marks = marks_n * 2
print doubled_marks

[16 16 20  4  6 20  2 12 14 16]


In [12]:
print marks_n
print marks_n[0]
print marks_n[4]
print marks_n[[0, 2, 4]] # numpy allows us to access multiple indexes in an argument


[ 8  8 10  2  3 10  1  6  7  8]
8
3
[ 8 10  3]


In [15]:
print marks_n
first_three = marks_n[:3]
print first_three # slicing # however numpy refers a copy and does nor create another copy if we create a variable

[ 8  8 10  2  3 10  1  6  7  8]
[ 8  8 10]


In [17]:
first_three[0] = 7
print first_three
print marks_n # by editing first_three, it actually appended in marks_n since numpy does nor create a new variable when sliced.

[ 7  8 10]
[ 7  8 10  2  3 10  1  6  7  8]


In [18]:
print marks_n[0:len(marks_n):2]

[ 7 10  3  1  7]


In [20]:
print marks_n[::2]

[ 7 10  3  1  7]


In [25]:
print marks_n.mean() #mean
print marks_n.std() #standard deviation
print marks_n.var() # variance(square of std)
print marks_n.cumsum() # cummulative sum
print marks_n.max() # gives maximum value in numpy array

6.2
3.02654919008
9.16
[ 7 15 25 27 30 40 41 47 54 62]
10


In [30]:
marks_a = np.array([1, 3, 4, 5, 6, 9, 13, 24, 0])

In [31]:
print marks_a.nonzero() # removes non zero index element
non_zero_marks = marks_a[marks_a > 0]  # give us non zero marks or greater that 0 marks
print non_zero_marks

(array([0, 1, 2, 3, 4, 5, 6, 7], dtype=int64),)
[ 1  3  4  5  6  9 13 24]


In [32]:
print marks_a[(marks_a%2 == 0) | (marks_a > 5)]

[ 4  6  9 13 24  0]


In [37]:
#numpy also allows to change multiple index element

marks_n[[1, 6]] = [10, 67]
print marks_n

[ 7 10 10  2  3 10 67  6  7  8]


In [43]:
marks_n[[0, 1, 3]] -= 1
print marks_n

[ 6  9 10  1  3 10 67  6  7  8]


In [48]:
physics = np.array([95, 96, 81])
chemistry = np.array([55, 76, 71])
maths = np.array([75, 78, 51])

In [50]:
pcm = physics + chemistry + maths
print pcm

[225 250 203]


In [52]:
marks_n[[2, 5, 6]] = -1
print marks_n

[ 6  9 -1  1  3 -1 -1  6  7  8]


In [55]:
print np.where(marks_n >= 0, marks_n+1, marks_n) #np.where call numpy function and 
#its argument would be the array we want to modify

[ 7 10 -1  2  4 -1 -1  7  8  9]


In [ ]:
marks_n.

In [34]:
print marks_a

[ 1  3  4  5  6  9 13 24  0]
