In [1]:
import numpy as np

In [2]:
marks = [
    [89, 88, 67],
    [78, 67, 83],
    [69, 85, 99]
]

In [3]:
marks_n = np.array(marks)

In [6]:
print marks_n
print type(marks_n)
print marks_n.shape
print marks_n.dtype

[[89 88 67]
 [78 67 83]
 [69 85 99]]
<type 'numpy.ndarray'>
(3L, 3L)
int32


In [12]:
print marks_n[0]
print marks_n[[0, 2]] # double brackets gives indexes
print marks_n[1, 2] # single bracket give index and its element


[89 88 67]
[[89 88 67]
 [69 85 99]]
83


In [16]:
print marks_n[0:2] #row slicing
print marks_n[0:2, 0:2] #row and column slicing.
print marks_n[:2, :2]

[[89 88 67]
 [78 67 83]]
[[89 88]
 [78 67]]
[[89 88]
 [78 67]]


In [11]:
print marks_n
#print marks_n[1:, 1:]
#print marks_n[:3, 2:]
#print marks_n[:2, [0, 2]]# also enable us slicing rows and then skip
print marks_n[[0, 2], ::2]

[[89 88 67]
 [78 67 83]
 [69 85 99]]
[[89 67]
 [69 99]]


In [14]:
print marks_n
print marks_n.sum(axis=1) #axis=1 is row addition
print marks_n.mean(axis=0) # axis=0 is column addition

[[89 88 67]
 [78 67 83]
 [69 85 99]]
[244 228 253]
[ 78.66666667  80.          83.        ]


In [18]:
print marks_n
grace_marks = np.array([5, 0, 10])
print marks_n + grace_marks #this is called broadcasting where one dimensional array is added to 2 dimensional arrray element by element'''


[[89 88 67]
 [78 67 83]
 [69 85 99]]
[[ 94  88  77]
 [ 83  67  93]
 [ 74  85 109]]


In [20]:
marks_m = np.array([
    [56, 49, 67],
    [89, 70, 80]
    ])

In [21]:
print marks_n
print marks_m

[[89 88 67]
 [78 67 83]
 [69 85 99]]
[[56 49 67]
 [89 70 80]]


In [26]:
all_marks = np.vstack((marks_n, marks_m)) # this joins two data set or merge them vertically hence, vstack
print all_marks

[[89 88 67]
 [78 67 83]
 [69 85 99]
 [56 49 67]
 [89 70 80]]


In [28]:
print all_marks.mean(axis=0)

[ 76.2  71.8  79.2]


In [30]:
print marks_n
aptitude = np.array([
    [45, 56],
    [67, 100],
    [99, 46]
])
print aptitude

[[89 88 67]
 [78 67 83]
 [69 85 99]]
[[ 45  56]
 [ 67 100]
 [ 99  46]]


In [32]:
all_students = np.hstack((marks_n, aptitude)) # this joins two data set or merge them horizontally hence, hstack
print all_students

[[ 89  88  67  45  56]
 [ 78  67  83  67 100]
 [ 69  85  99  99  46]]


In [33]:
a = np.array([
    [4, 5],
    [6, 8]
])
b = np.array([
    [2,3],
    [1, 4]
])

In [37]:
print a
print b
print a + b
print a - b
print a * b #numpy does element to element mapping for mathematical ops like these
#in case we have to perform matrix multiplication, use dot method. matrix multiplication is row * column
print np.dot(a, b)

[[4 5]
 [6 8]]
[[2 3]
 [1 4]]
[[ 6  8]
 [ 7 12]]
[[2 2]
 [5 4]]
[[ 8 15]
 [ 6 32]]
[[13 32]
 [20 50]]


In [41]:
marks = np.genfromtxt('marks.csv', delimiter=',')
print marks
#nan is not a number. numpy treats this as float.

[[ nan  10.  nan]
 [ nan  15.  nan]
 [ nan  20.  nan]]


In [46]:
only_marks = marks[:, 1:2]
print only_marks
print only_marks.mean()

[[ 10.]
 [ 15.]
 [ 20.]]
15.0
