In [1]:
import numpy as np

In [2]:
import numpy.random as rd

In [4]:
r1 = rd.randn(3,3)

In [5]:
print r1

[[ 0.06998695 -0.69212469 -0.42416907]
 [-0.07572376 -1.15077166 -0.34277273]
 [ 0.34883807  1.78861806 -0.60753124]]
